# -*- coding: utf-8 -*-
"""Custom UI definition for Poseidon controller GUI with four pumps."""
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(16, 16, 16, 16)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.control = QtWidgets.QWidget()
        self.control.setObjectName("control")
        self.controlLayout = QtWidgets.QVBoxLayout(self.control)
        self.controlLayout.setSpacing(18)
        self.controlLayout.setObjectName("controlLayout")

        self.pumpGrid = QtWidgets.QGridLayout()
        self.pumpGrid.setHorizontalSpacing(18)
        self.pumpGrid.setVerticalSpacing(18)
        self.pumpGrid.setObjectName("pumpGrid")
        self.controlLayout.addLayout(self.pumpGrid)

        self._create_pump_groups()

        self.line_control = QtWidgets.QFrame(self.control)
        self.line_control.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_control.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_control.setLineWidth(2)
        self.line_control.setObjectName("line_control")
        self.controlLayout.addWidget(self.line_control)

        self.actionButtonsLayout = QtWidgets.QHBoxLayout()
        self.actionButtonsLayout.setSpacing(16)
        self.actionButtonsLayout.setObjectName("actionButtonsLayout")
        self.run_BTN = self._create_action_button("run_BTN", self.control)
        self.actionButtonsLayout.addWidget(self.run_BTN)
        self.pause_BTN = self._create_action_button("pause_BTN", self.control)
        self.actionButtonsLayout.addWidget(self.pause_BTN)
        self.zero_BTN = self._create_action_button("zero_BTN", self.control)
        self.actionButtonsLayout.addWidget(self.zero_BTN)
        self.stop_BTN = self._create_action_button("stop_BTN", self.control)
        self.actionButtonsLayout.addWidget(self.stop_BTN)
        self.controlLayout.addLayout(self.actionButtonsLayout)

        self.jogLayout = QtWidgets.QHBoxLayout()
        self.jogLayout.setSpacing(20)
        self.jogLayout.setObjectName("jogLayout")
        self.jog_minus_BTN = self._create_jog_button("jog_minus_BTN", self.control)
        self.jogLayout.addWidget(self.jog_minus_BTN)

        self.coordLayout = QtWidgets.QHBoxLayout()
        self.coordLayout.setObjectName("coordLayout")
        self.coordLabel = QtWidgets.QLabel(self.control)
        self.coordLabel.setObjectName("coordLabel")
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        self.coordLabel.setFont(font)
        self.coordLayout.addWidget(self.coordLabel)
        self.absolute_RADIO = QtWidgets.QRadioButton(self.control)
        self.absolute_RADIO.setObjectName("absolute_RADIO")
        font = QtGui.QFont()
        font.setPointSize(14)
        self.absolute_RADIO.setFont(font)
        self.absolute_RADIO.setChecked(True)
        self.coordLayout.addWidget(self.absolute_RADIO)
        self.incremental_RADIO = QtWidgets.QRadioButton(self.control)
        self.incremental_RADIO.setObjectName("incremental_RADIO")
        self.incremental_RADIO.setFont(font)
        self.coordLayout.addWidget(self.incremental_RADIO)
        self.jogLayout.addLayout(self.coordLayout)

        self.jog_plus_BTN = self._create_jog_button("jog_plus_BTN", self.control)
        self.jogLayout.addWidget(self.jog_plus_BTN)
        self.controlLayout.addLayout(self.jogLayout)

        self.tabWidget.addTab(self.control, "")

        self.setup = QtWidgets.QWidget()
        self.setup.setObjectName("setup")
        self.setupLayout = QtWidgets.QVBoxLayout(self.setup)
        self.setupLayout.setSpacing(16)
        self.setupLayout.setObjectName("setupLayout")

        self.portGrid = QtWidgets.QGridLayout()
        self.portGrid.setObjectName("portGrid")

        self.primaryControllerGroup = QtWidgets.QGroupBox(self.setup)
        self.primaryControllerGroup.setObjectName("primaryControllerGroup")
        self.primaryControllerLayout = QtWidgets.QVBoxLayout(self.primaryControllerGroup)
        self.primaryControllerLayout.setSpacing(8)
        self.primaryControllerLayout.setObjectName("primaryControllerLayout")
        font = QtGui.QFont()
        font.setPointSize(12)
        self.primary_status_LABEL = QtWidgets.QLabel(self.primaryControllerGroup)
        self.primary_status_LABEL.setFont(font)
        self.primary_status_LABEL.setObjectName("primary_status_LABEL")
        self.primaryControllerLayout.addWidget(self.primary_status_LABEL)
        self.primaryPortLayout = QtWidgets.QHBoxLayout()
        self.primaryPortLayout.setObjectName("primaryPortLayout")
        self.primary_port_DROPDOWN = QtWidgets.QComboBox(self.primaryControllerGroup)
        self.primary_port_DROPDOWN.setObjectName("primary_port_DROPDOWN")
        self.primaryPortLayout.addWidget(self.primary_port_DROPDOWN)
        self.primary_connect_BTN = QtWidgets.QPushButton(self.primaryControllerGroup)
        self.primary_connect_BTN.setObjectName("primary_connect_BTN")
        self.primaryPortLayout.addWidget(self.primary_connect_BTN)
        self.primary_disconnect_BTN = QtWidgets.QPushButton(self.primaryControllerGroup)
        self.primary_disconnect_BTN.setEnabled(False)
        self.primary_disconnect_BTN.setObjectName("primary_disconnect_BTN")
        self.primaryPortLayout.addWidget(self.primary_disconnect_BTN)
        self.primaryControllerLayout.addLayout(self.primaryPortLayout)
        self.portGrid.addWidget(self.primaryControllerGroup, 0, 0)

        self.secondaryControllerGroup = QtWidgets.QGroupBox(self.setup)
        self.secondaryControllerGroup.setObjectName("secondaryControllerGroup")
        self.secondaryControllerLayout = QtWidgets.QVBoxLayout(self.secondaryControllerGroup)
        self.secondaryControllerLayout.setSpacing(8)
        self.secondaryControllerLayout.setObjectName("secondaryControllerLayout")
        self.secondary_status_LABEL = QtWidgets.QLabel(self.secondaryControllerGroup)
        self.secondary_status_LABEL.setFont(font)
        self.secondary_status_LABEL.setObjectName("secondary_status_LABEL")
        self.secondaryControllerLayout.addWidget(self.secondary_status_LABEL)
        self.secondaryPortLayout = QtWidgets.QHBoxLayout()
        self.secondaryPortLayout.setObjectName("secondaryPortLayout")
        self.secondary_port_DROPDOWN = QtWidgets.QComboBox(self.secondaryControllerGroup)
        self.secondary_port_DROPDOWN.setObjectName("secondary_port_DROPDOWN")
        self.secondaryPortLayout.addWidget(self.secondary_port_DROPDOWN)
        self.secondary_connect_BTN = QtWidgets.QPushButton(self.secondaryControllerGroup)
        self.secondary_connect_BTN.setObjectName("secondary_connect_BTN")
        self.secondaryPortLayout.addWidget(self.secondary_connect_BTN)
        self.secondary_disconnect_BTN = QtWidgets.QPushButton(self.secondaryControllerGroup)
        self.secondary_disconnect_BTN.setEnabled(False)
        self.secondary_disconnect_BTN.setObjectName("secondary_disconnect_BTN")
        self.secondaryPortLayout.addWidget(self.secondary_disconnect_BTN)
        self.secondaryControllerLayout.addLayout(self.secondaryPortLayout)
        self.portGrid.addWidget(self.secondaryControllerGroup, 0, 1)

        self.portButtonsLayout = QtWidgets.QHBoxLayout()
        self.portButtonsLayout.setObjectName("portButtonsLayout")
        spacer_port_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.portButtonsLayout.addItem(spacer_port_left)
        self.refresh_ports_BTN = QtWidgets.QPushButton(self.setup)
        self.refresh_ports_BTN.setObjectName("refresh_ports_BTN")
        self.portButtonsLayout.addWidget(self.refresh_ports_BTN)
        spacer_port_right = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.portButtonsLayout.addItem(spacer_port_right)
        self.portGrid.addLayout(self.portButtonsLayout, 1, 0, 1, 2)
        self.setupLayout.addLayout(self.portGrid)

        self.microsteppingLayout = QtWidgets.QHBoxLayout()
        self.microsteppingLayout.setObjectName("microsteppingLayout")
        self.label_5 = QtWidgets.QLabel(self.setup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.microsteppingLayout.addWidget(self.label_5)
        self.microstepping_DROPDOWN = QtWidgets.QComboBox(self.setup)
        self.microstepping_DROPDOWN.setObjectName("microstepping_DROPDOWN")
        self.microsteppingLayout.addWidget(self.microstepping_DROPDOWN)
        self.setupLayout.addLayout(self.microsteppingLayout)

        self.line_6 = QtWidgets.QFrame(self.setup)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.setupLayout.addWidget(self.line_6)

        self.setupGrid = QtWidgets.QGridLayout()
        self.setupGrid.setHorizontalSpacing(12)
        self.setupGrid.setVerticalSpacing(12)
        self.setupGrid.setObjectName("setupGrid")
        self.setupLayout.addLayout(self.setupGrid)
        self._create_setup_headers()
        self._create_setup_rows()

        self.calibrationLayout = QtWidgets.QHBoxLayout()
        self.calibrationLayout.setObjectName("calibrationLayout")
        spacer_cal_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.calibrationLayout.addItem(spacer_cal_left)
        self.calibrate_syringe_BTN = QtWidgets.QPushButton(self.setup)
        self.calibrate_syringe_BTN.setObjectName("calibrate_syringe_BTN")
        self.calibrationLayout.addWidget(self.calibrate_syringe_BTN)
        spacer_cal_right = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.calibrationLayout.addItem(spacer_cal_right)
        self.setupLayout.addLayout(self.calibrationLayout)

        self.sendAllLayout = QtWidgets.QHBoxLayout()
        self.sendAllLayout.setObjectName("sendAllLayout")
        spacer_send_left = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sendAllLayout.addItem(spacer_send_left)
        self.send_all_BTN = QtWidgets.QPushButton(self.setup)
        self.send_all_BTN.setObjectName("send_all_BTN")
        self.sendAllLayout.addWidget(self.send_all_BTN)
        spacer_send_right = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.sendAllLayout.addItem(spacer_send_right)
        self.setupLayout.addLayout(self.sendAllLayout)

        self.experiment_notes = QtWidgets.QLineEdit(self.setup)
        self.experiment_notes.setObjectName("experiment_notes")
        self.setupLayout.addWidget(self.experiment_notes)

        self.tabWidget.addTab(self.setup, "")

        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.status_bar_DISP = QtWidgets.QStatusBar(MainWindow)
        self.status_bar_DISP.setObjectName("status_bar_DISP")
        MainWindow.setStatusBar(self.status_bar_DISP)

        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)

        self.load_settings_BTN = QtWidgets.QAction(MainWindow)
        self.load_settings_BTN.setObjectName("load_settings_BTN")
        self.save_settings_BTN = QtWidgets.QAction(MainWindow)
        self.save_settings_BTN.setObjectName("save_settings_BTN")
        self.menuFile.addAction(self.load_settings_BTN)
        self.menuFile.addAction(self.save_settings_BTN)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def _create_pump_groups(self):
        font_group = QtGui.QFont()
        font_group.setPointSize(14)
        font_group.setBold(True)
        font_title = QtGui.QFont()
        font_title.setPointSize(12)
        font_value = QtGui.QFont()
        font_value.setPointSize(12)
        for index in range(4):
            pump_id = index + 1
            group = QtWidgets.QGroupBox(self.control)
            group.setObjectName(f"pump{pump_id}Group")
            group.setFont(font_group)
            layout = QtWidgets.QGridLayout(group)
            layout.setHorizontalSpacing(12)
            layout.setVerticalSpacing(10)
            layout.setObjectName(f"gridLayout_p{pump_id}")

            checkbox = QtWidgets.QCheckBox(group)
            checkbox.setObjectName(f"p{pump_id}_activate_CHECKBOX")
            checkbox.setFont(font_value)
            layout.addWidget(checkbox, 0, 0, 1, 3)

            syringe_title = QtWidgets.QLabel(group)
            syringe_title.setObjectName(f"p{pump_id}_syringe_title")
            syringe_title.setFont(font_title)
            layout.addWidget(syringe_title, 1, 0, 1, 1)
            setattr(self, f"p{pump_id}_syringe_title", syringe_title)

            syringe_label = QtWidgets.QLabel(group)
            syringe_label.setObjectName(f"p{pump_id}_syringe_LABEL")
            syringe_label.setFont(font_value)
            layout.addWidget(syringe_label, 1, 1, 1, 2)

            speed_title = QtWidgets.QLabel(group)
            speed_title.setObjectName(f"p{pump_id}_speed_title")
            speed_title.setFont(font_title)
            layout.addWidget(speed_title, 2, 0, 1, 1)
            setattr(self, f"p{pump_id}_speed_title", speed_title)

            speed_label = QtWidgets.QLabel(group)
            speed_label.setObjectName(f"p{pump_id}_units_LABEL")
            speed_label.setFont(font_value)
            layout.addWidget(speed_label, 2, 1, 1, 2)

            amount_title = QtWidgets.QLabel(group)
            amount_title.setObjectName(f"p{pump_id}_amount_title")
            amount_title.setFont(font_title)
            layout.addWidget(amount_title, 3, 0, 1, 1)
            setattr(self, f"p{pump_id}_amount_title", amount_title)

            amount_input = QtWidgets.QDoubleSpinBox(group)
            amount_input.setObjectName(f"p{pump_id}_amount_INPUT")
            amount_input.setFont(font_value)
            amount_input.setDecimals(3)
            amount_input.setMinimum(-999.0)
            amount_input.setMaximum(999.0)
            amount_input.setMinimumSize(QtCore.QSize(0, 40))
            layout.addWidget(amount_input, 3, 1, 1, 1)

            amount_units = QtWidgets.QLabel(group)
            amount_units.setObjectName(f"p{pump_id}_units_LABEL_2")
            amount_units.setFont(font_value)
            layout.addWidget(amount_units, 3, 2, 1, 1)

            absolute_title = QtWidgets.QLabel(group)
            absolute_title.setObjectName(f"p{pump_id}_absolute_title")
            absolute_title.setFont(font_title)
            layout.addWidget(absolute_title, 4, 0, 1, 1)
            setattr(self, f"p{pump_id}_absolute_title", absolute_title)

            absolute_disp = QtWidgets.QLCDNumber(group)
            absolute_disp.setObjectName(f"p{pump_id}_absolute_DISP")
            absolute_disp.setDigitCount(7)
            absolute_disp.setMinimumSize(QtCore.QSize(160, 50))
            layout.addWidget(absolute_disp, 4, 1, 1, 2)

            incremental_title = QtWidgets.QLabel(group)
            incremental_title.setObjectName(f"p{pump_id}_incremental_title")
            incremental_title.setFont(font_title)
            layout.addWidget(incremental_title, 5, 0, 1, 1)
            setattr(self, f"p{pump_id}_incremental_title", incremental_title)

            incremental_disp = QtWidgets.QLCDNumber(group)
            incremental_disp.setObjectName(f"p{pump_id}_incremental_DISP")
            incremental_disp.setDigitCount(7)
            incremental_disp.setMinimumSize(QtCore.QSize(160, 50))
            layout.addWidget(incremental_disp, 5, 1, 1, 2)

            remain_title = QtWidgets.QLabel(group)
            remain_title.setObjectName(f"p{pump_id}_remain_title")
            remain_title.setFont(font_title)
            layout.addWidget(remain_title, 6, 0, 1, 1)
            setattr(self, f"p{pump_id}_remain_title", remain_title)

            remain_disp = QtWidgets.QLCDNumber(group)
            remain_disp.setObjectName(f"p{pump_id}_remain_DISP")
            remain_disp.setDigitCount(7)
            remain_disp.setMinimumSize(QtCore.QSize(160, 50))
            layout.addWidget(remain_disp, 6, 1, 1, 2)

            row = index // 2
            col = index % 2
            self.pumpGrid.addWidget(group, row, col, 1, 1)

            setattr(self, f"pump{pump_id}Group", group)
            setattr(self, f"p{pump_id}_activate_CHECKBOX", checkbox)
            setattr(self, f"p{pump_id}_syringe_LABEL", syringe_label)
            setattr(self, f"p{pump_id}_units_LABEL", speed_label)
            setattr(self, f"p{pump_id}_amount_INPUT", amount_input)
            setattr(self, f"p{pump_id}_units_LABEL_2", amount_units)
            setattr(self, f"p{pump_id}_absolute_DISP", absolute_disp)
            setattr(self, f"p{pump_id}_incremental_DISP", incremental_disp)
            setattr(self, f"p{pump_id}_remain_DISP", remain_disp)

    def _create_setup_headers(self):
        header_font = QtGui.QFont()
        header_font.setPointSize(12)
        header_font.setBold(True)
        headers = [
            ("label_16", "Syringe"),
            ("label_10", "Units"),
            ("label_24", "Speed"),
            ("label_19", "Accel"),
            ("label_58", "Jog Δ"),
            ("label_send", "Send"),
        ]
        for column, (name, text) in enumerate(headers):
            label = QtWidgets.QLabel(self.setup)
            label.setObjectName(name)
            label.setFont(header_font)
            label.setAlignment(QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
            self.setupGrid.addWidget(label, 0, column, 1, 1)
            setattr(self, name, label)

    def _create_setup_rows(self):
        for index in range(4):
            pump_id = index + 1
            row = index + 1
            syringe_dropdown = QtWidgets.QComboBox(self.setup)
            syringe_dropdown.setObjectName(f"p{pump_id}_syringe_DROPDOWN")
            self.setupGrid.addWidget(syringe_dropdown, row, 0, 1, 1)

            units_dropdown = QtWidgets.QComboBox(self.setup)
            units_dropdown.setObjectName(f"p{pump_id}_units_DROPDOWN")
            self.setupGrid.addWidget(units_dropdown, row, 1, 1, 1)

            speed_input = QtWidgets.QDoubleSpinBox(self.setup)
            speed_input.setObjectName(f"p{pump_id}_speed_INPUT")
            speed_input.setDecimals(4)
            speed_input.setMaximum(9999.999)
            self.setupGrid.addWidget(speed_input, row, 2, 1, 1)

            accel_input = QtWidgets.QDoubleSpinBox(self.setup)
            accel_input.setObjectName(f"p{pump_id}_accel_INPUT")
            accel_input.setMaximum(99999.999)
            self.setupGrid.addWidget(accel_input, row, 3, 1, 1)

            jog_dropdown = QtWidgets.QComboBox(self.setup)
            jog_dropdown.setObjectName(f"p{pump_id}_setup_jog_delta_INPUT")
            self.setupGrid.addWidget(jog_dropdown, row, 4, 1, 1)

            send_button = QtWidgets.QPushButton(self.setup)
            send_button.setObjectName(f"p{pump_id}_setup_send_BTN")
            self.setupGrid.addWidget(send_button, row, 5, 1, 1)

            setattr(self, f"p{pump_id}_syringe_DROPDOWN", syringe_dropdown)
            setattr(self, f"p{pump_id}_units_DROPDOWN", units_dropdown)
            setattr(self, f"p{pump_id}_speed_INPUT", speed_input)
            setattr(self, f"p{pump_id}_accel_INPUT", accel_input)
            setattr(self, f"p{pump_id}_setup_jog_delta_INPUT", jog_dropdown)
            setattr(self, f"p{pump_id}_setup_send_BTN", send_button)

    def _create_action_button(self, name, parent):
        button = QtWidgets.QPushButton(parent)
        button.setObjectName(name)
        button.setMinimumSize(QtCore.QSize(160, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        button.setFont(font)
        return button

    def _create_jog_button(self, name, parent):
        button = QtWidgets.QPushButton(parent)
        button.setObjectName(name)
        button.setMinimumSize(QtCore.QSize(140, 70))
        font = QtGui.QFont()
        font.setPointSize(16)
        button.setFont(font)
        return button

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Poseidon Controller"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.control), _translate("MainWindow", "Control"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.setup), _translate("MainWindow", "Setup"))

        for pump_id in range(1, 5):
            getattr(self, f"pump{pump_id}Group").setTitle(_translate("MainWindow", f"Pump {pump_id}"))
            getattr(self, f"p{pump_id}_activate_CHECKBOX").setText(_translate("MainWindow", "Enable"))
            getattr(self, f"p{pump_id}_syringe_title").setText(_translate("MainWindow", "Syringe"))
            getattr(self, f"p{pump_id}_syringe_LABEL").setText(_translate("MainWindow", "Not set"))
            getattr(self, f"p{pump_id}_speed_title").setText(_translate("MainWindow", "Speed"))
            getattr(self, f"p{pump_id}_units_LABEL").setText(_translate("MainWindow", "0.0"))
            getattr(self, f"p{pump_id}_amount_title").setText(_translate("MainWindow", "Amount"))
            getattr(self, f"p{pump_id}_units_LABEL_2").setText(_translate("MainWindow", "[units]"))
            getattr(self, f"p{pump_id}_absolute_title").setText(_translate("MainWindow", "Absolute"))
            getattr(self, f"p{pump_id}_incremental_title").setText(_translate("MainWindow", "Incremental"))
            getattr(self, f"p{pump_id}_remain_title").setText(_translate("MainWindow", "Remain"))

        self.run_BTN.setText(_translate("MainWindow", "Run"))
        self.pause_BTN.setText(_translate("MainWindow", "Pause"))
        self.zero_BTN.setText(_translate("MainWindow", "Zero"))
        self.stop_BTN.setText(_translate("MainWindow", "STOP"))
        self.jog_minus_BTN.setText(_translate("MainWindow", "Jog -"))
        self.coordLabel.setText(_translate("MainWindow", "Coordinate"))
        self.absolute_RADIO.setText(_translate("MainWindow", "Abs."))
        self.incremental_RADIO.setText(_translate("MainWindow", "Incr."))
        self.jog_plus_BTN.setText(_translate("MainWindow", "Jog +"))

        self.primaryControllerGroup.setTitle(_translate("MainWindow", "CNC Shield A"))
        self.primary_status_LABEL.setText(_translate("MainWindow", "Disconnected"))
        self.primary_connect_BTN.setText(_translate("MainWindow", "Connect"))
        self.primary_disconnect_BTN.setText(_translate("MainWindow", "Disconnect"))
        self.secondaryControllerGroup.setTitle(_translate("MainWindow", "CNC Shield B"))
        self.secondary_status_LABEL.setText(_translate("MainWindow", "Disconnected"))
        self.secondary_connect_BTN.setText(_translate("MainWindow", "Connect"))
        self.secondary_disconnect_BTN.setText(_translate("MainWindow", "Disconnect"))
        self.refresh_ports_BTN.setText(_translate("MainWindow", "Refresh ports"))
        self.label_5.setText(_translate("MainWindow", "Set Microstepping:"))
        self.label_16.setText(_translate("MainWindow", "Syringe"))
        self.label_10.setText(_translate("MainWindow", "Units"))
        self.label_24.setText(_translate("MainWindow", "Speed"))
        self.label_19.setText(_translate("MainWindow", "Accel"))
        self.label_58.setText(_translate("MainWindow", "Jog Δ"))
        self.label_send.setText(_translate("MainWindow", "Send"))

        for pump_id in range(1, 5):
            getattr(self, f"p{pump_id}_setup_send_BTN").setText(_translate("MainWindow", "Send"))

        self.calibrate_syringe_BTN.setText(_translate("MainWindow", "Calibrate Syringe..."))
        self.send_all_BTN.setText(_translate("MainWindow", "Send all settings"))
        self.experiment_notes.setPlaceholderText(_translate(
            "MainWindow",
            "Write notes about your experiment here. These will be appended to the end of your settings file."))

        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.load_settings_BTN.setText(_translate("MainWindow", "Load settings"))
        self.save_settings_BTN.setText(_translate("MainWindow", "Save settings"))
